---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse, quietly = TRUE)
```
```{r county_maps}
library(tidyverse, quietly = TRUE)
library(sf, quietly = TRUE)
library(tigris, quietly = TRUE)
library(tidycensus, quietly = TRUE)
library(viridis, quietly = TRUE)
options(tigris_use_cache = TRUE)
library(ggrepel)
options(tigris_class = "sf")

path_to_post <- "~/Dropbox/Programming/R_Stuff/can_i_blog_too/content/post/2020-03-29-covid19-cases-in-connecticut/"

```
```{r census_stuff}
if (!exists("county_geometries")) load("ct_population.RData")
if (!exists("county_geometries")) {
  county_geometries <- counties(state = "CT", cb = FALSE)
  ct_population <- get_acs(geography = "county", 
                           variables = "B01003_001", 
                           state = "CT",
                           geometry = TRUE) %>% 
    mutate(county = str_replace(NAME, " County, Connecticut", ""))
  # save(county_geometries, ct_population, file = "ct_population.RData")
}
```

 Note: Kieran Healey on tracking Covid-19:
 https://kieranhealy.org/blog/archives/2020/03/21/covid-19-tracking/

```{r}
# from https://github.com/nytimes/covid-19-data
counties <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
ct0 <- counties %>%
  filter(state == "Connecticut")


manual_supplement <- tibble(
  date = c(rep(as.Date("2020-03-28"), 9), rep(as.Date("2020-03-29"), 9),
  rep(as.Date("2020-03-30"), 9),
  rep(as.Date("2020-03-31"), 9),
  rep(as.Date("2020-04-01"), 9),
  rep(as.Date("2020-04-02"), 9),
  rep(as.Date("2020-04-03"), 9),
  rep(as.Date("2020-04-04"), 9),
  rep(as.Date("2020-04-05"), 9),
  rep(as.Date("2020-04-06"), 9),
  rep(as.Date("2020-04-07"), 9)),
  county = rep(c("Fairfield", "Hartford", "Litchfield", "Middlesex", "New Haven", "New London", "Tolland", "Windham", "Unknown"), 11),
  cases = c(908, 228, 65, 28, 236, 19, 37, 3, 0,
            1245, 276, 87, 38, 280, 20, 40, 7, 0,
            1445, 330, 113, 59, 373, 24, 50, 10, 0,
            1870, 393, 121, 56, 517, 27, 56, 11, 0,
            1986, 469, 131, 66, 611, 29, 61, 19, 185,
            2132, 539, 141, 74, 647, 29, 67, 21, 174,
            2716, 679, 173, 91, 891, 40, 79, 27, 218,
            2824, 726, 182, 100, 1024, 57, 91, 31,241,
            3050, 751, 197, 110, 1162, 57, 94, 32, 222,
            3719, 882, 230, 135, 1468, 65, 103, 40, 264,
            4136, 1045, 255, 150, 1664, 85, 111, 43, 292
            ),
  deaths = c(20, 2, 0, 1, 6, 0, 4, 0, 0,
             21, 2, 0, 1, 6, 0, 4, 0, 0,
             21, 3, 1, 1, 6, 0, 4, 0, 0,
             38, 7, 1, 1, 12, 1, 7, 0, 0,
             46, 11, 1, 2, 15, 1, 7, 0, 2,
             65, 13, 2, 3, 17, 1, 10, 0, 1,
             75, 18, 4, 2, 18, 3, 10, 0, 1,
             86, 26, 5, 4, 29, 3, 10, 1, 1,
             96, 29, 6, 5, 36, 4, 11, 1, 1,
             101, 31, 8, 7, 41, 4, 13, 1, 0,
             132, 48, 9, 7, 60, 4, 13, 1, 3)
) %>% 
  filter(date > max(ct0$date)) %>% 
  mutate(state = "Connecticut")

hospital <- tribble(
~date, ~Litchfield, ~Harford, ~Tolland, ~Windham, ~Fairfield, ~`New Haven`, ~Middlesex, ~`New London`,
"3/21/2020",2,12,2,0,15,9,3,0,
"3/22/2020",3,13,2,0,20,9,3,1,
"3/23/2020",2,13,2,0,20,12,4,1,
"3/24/2020",3,17,4,0,23,19,4,1,
"3/25/2020",3,24,5,0,47,28,4,2,
"3/26/2020",3,27,5,0,49,34,5,2,
"3/27/2020",9,36,7,0,68,46,5,2,
"3/28/2020",12,41,7,0,88,50,5,2,
"3/29/2020",5,67,0,1,189,137,1,4,
"3/30/2020",7,96,2,0,230,176,1,5,
"3/31/2020",7,110,1,0,275,202,5,8,
"4/1/2020",11,126,1,0,359,251,8,10,
"4/2/2020",11,136,2,3,381,274,11,9,
"4/3/2020",14,166,3,3,409,293,12,9,
"4/4/2020",15,184,3,3,475,324,19,10,
"4/5/2020",15,189,3,3,531,372,19,10,
"4/6/2020",15,213,3,2,572,384,22,10,
"4/7/2020",17,243,4,3,613,390,26,12
) %>% 
  mutate(date = mdy(date)) %>% 
  pivot_longer(-date, names_to = "county", values_to = "hospital")

if (nrow(manual_supplement) > 0) ct1 <- bind_rows(ct0, manual_supplement)
print(paste("Check totals:", max(ct1$date), "cases:", sum(ct1$cases[ct1$date == max(ct1$date)]),
      "deaths:", sum(ct1$deaths[ct1$date == max(ct1$date)])))
```
March 10 -- executive order 7: prohibited large gatherings
March 17 order 7C: cancelled classes
March 23 order 7H: restrict nonessential business
March 26 order 7N: limit gathering to 5 or fewer

hospitalizations = 43  54  71 113 125 173 173 404 517 608 766 starting "2020-03-20"

```{r}



```


```{r}
ct2 <- ct1 %>%
  left_join(hospital, by = c("date", "county")) %>% 
  filter(state == "Connecticut", county != "Unknown")
exec_orders <- tibble(
  date = as.Date(c("2020-03-10", "2020-03-17", "2020-03-23", "2020-03-26")),
  label = c("prohibit large\ngatherings", "cancel\nclasses", "restrict\nbusiness", "5 or fewer")
) %>% 
  left_join(ct %>% filter(county == "Fairfield") %>% select(date, cases), by = "date") %>% 
  mutate(county = "Fairfield")
ct <- ct2 %>% 
  mutate(county = fct_reorder2(county, date, cases))
date_range <- unique(ct$date)
label_height_cases <- function(county, date) {
  # ht <- ct$cases[(ct$county == county) & (ct$date == date)]
  ht <- ct$cases[(ct$county == county) & (ct$date == max(ct$date))]
  # ht <- ct$cases[(ct$county == county) & (ct$date == date_range[length(date_range) - 2])]
  if (length(ht) == 0) ht <- 0.5
  return(ht)
}
label_height_deaths <- function(county, date) {
  ht <- ct$deaths[(ct$county == county) & (ct$date == max(ct$date))]
  if (length(ht) == 0) ht <- 0.5
  return(ht)
}
label_height_hospital <- function(county, date) {
  ht <- ct$hospital[(ct$county == county) & (ct$date == max(ct$date))]
  if (length(ht) == 0) ht <- 0.5
  return(ht)
}
for_labels <- tibble(
  # date = date_range[seq(length(date_range) - 2 + 1, length(date_range) - 1 + 1 - length(unique(ct$county)), -1)],
  date = max(date_range),
  county = levels(ct$county),
  cases = 0,
  deaths = 0,
  hospital = 0
) %>% 
  mutate(cases = map2_dbl(county, date, label_height_cases),
         deaths = map2_dbl(county, date, label_height_deaths),
         hospital = map2_dbl(county, date, label_height_hospital))
# log minor breaks taken from https://stackoverflow.com/questions/30179442/plotting-minor-breaks-on-a-log-scale-with-ggplot
log10_minor_break = function (...){
  function(x) {
    minx         = floor(min(log10(x), na.rm=T))-1;
    maxx         = ceiling(max(log10(x), na.rm=T))+1;
    n_major      = maxx-minx+1;
    major_breaks = seq(minx, maxx, by=1)
    minor_breaks = 
      rep(log10(seq(1, 9, by=1)), times = n_major)+
      rep(major_breaks, each = 9)
    return(10^(minor_breaks))
  }
}
pcases <- ggplot(data = ct, aes(x = date, y = cases, colour = county)) + 
  geom_point() + geom_line() + xlab(NULL) +
    scale_x_date(date_minor_breaks = "1 day") +
  theme_minimal() + 
  theme(legend.position = "none")

pcases <- pcases + geom_text_repel(data = for_labels, aes(label = county), 
                         hjust = 0, vjust = 0.5, 
                         # check_overlap = FALSE, 
                         show.legend = FALSE, 
                         # nudge_x = 0.21,
                         direction = "y") + 
  expand_limits(x = max(ct$date) + 1) +
labs(
  title = "Cumulative COVID19 Cases in Connecticut by County",
  subtitle = NULL,
  caption = "Source: https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html"
)
pcases_nonlog <- pcases  + 
  ylab("confirmed cases")
    # annotation_custom(grob = ggplotGrob(county_map), xmin = date_range[2], xmax = date_range[13], 
    #                   ymin = 10 ^ (log10(max(ct$cases)) * 0.66), 
    #                   ymax = max(ct$cases))
pcases <- pcases +
  ylab("confirmed cases (log scale)") +
  scale_y_log10(minor_breaks=log10_minor_break()) +
  geom_text(data = exec_orders, aes(y = cases * 1.2, label = label), 
            hjust = 0.5, vjust = 0, size = 3, colour = "darkgrey")


pdeaths <- ggplot(data = ct %>% filter(deaths > 0) %>% 
                    mutate(deaths = ifelse(deaths == 0, NA_real_, deaths))
                  , aes(x = date, y = deaths, colour = county)) + 
  geom_point() + geom_line() + xlab(NULL) +
  scale_x_date(date_minor_breaks = "1 day", limits = c(min(ct$date), NA)) +
  theme_minimal() + 
  theme(legend.position = "none")

pdeaths <- pdeaths + geom_text_repel(data = for_labels %>% filter(deaths > 0), 
                                     aes(label = county), 
                                     hjust = 0, vjust = 0.5, 
                                     # check_overlap = FALSE, 
                                     show.legend = FALSE, 
                                     # nudge_x = 0.21,
                                     direction = "y") + 
  expand_limits(x = max(ct$date) + 1) 
pdeaths_log <- pdeaths +
  scale_y_log10(minor_breaks=log10_minor_break()) + 
  ylab("deaths (log scale)") +
  labs(
    title = "Cumulative COVID19 Deaths in Connecticut by County",
    subtitle = NULL,
    caption = "Source: https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html"
  )
pdeaths <- pdeaths + 
   ylab("deaths") +
  labs(
    title = "Cumulative COVID19 Deaths in Connecticut by County",
    subtitle = NULL,
    caption = "Source: https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html"
  )

phospital <- ggplot(data = ct2 %>% filter(!is.na(hospital)), 
                    aes(x = date, y = hospital, colour = county)) + 
  geom_point() + geom_line() + xlab(NULL) +
  scale_x_date(date_minor_breaks = "1 day", limits = c(min(ct$date), NA)) +
  theme_minimal() + 
  theme(legend.position = "none")
phospital <- phospital + geom_text_repel(data = for_labels %>% filter(deaths > 0), 
                                     aes(label = county), 
                                     hjust = 0, vjust = 0.5, 
                                     # check_overlap = FALSE, 
                                     show.legend = FALSE, 
                                     # nudge_x = 0.21,
                                     direction = "y")
 

```

```{r create_county_map}

ct_pop <- ct_population %>% 
  left_join(ct %>% filter(date == max(date))) %>% 
  mutate(cases_per_pop = cases / (estimate / 100000),
         per_pop_label =  as.character(round(cases_per_pop, 1)))
county_centroid <- st_centroid(ct_pop) # use to place town labels
county_map <- ggplot() + 
  geom_sf(data = ct_pop, aes(fill = cases_per_pop)) + 
  scale_fill_gradient(low = "white", high = "grey") +
  geom_sf_text(data = county_centroid, aes(label = paste0(county, "\n", per_pop_label, " per 100K")), color = "black", size = 3) +
  coord_sf(datum = NA, label_axes = "----") +
  xlab("") + ylab("") + theme_minimal()  +
  # theme(legend.position = "none") +
  labs(title = "Cumulative Confirmed Cases by Connecticut County",
       subtitle = "cases per 100K of population for most recent report date",
       fill = "cases per 100K",
       caption = "Source: US Census, tidycensus package")

```

```{r save_plots}
# this total for checking excludes "Unknown" county:
print(paste("Check totals:", max(ct$date), "cases:", sum(ct$cases[ct$date == max(ct$date)]),
      "deaths:", sum(ct$deaths
                     
                     [ct$date == max(ct$date)])))

ggsave("log_cases.png", plot = pcases, path = path_to_post,
       width = 7, height = 6, units = "in")

ggsave("cases_nonlog.png", plot = pcases_nonlog, path = path_to_post,
       width = 7, height = 6, units = "in")

ggsave("county_map.png", plot = county_map, path = path_to_post,
       width = 6, height = 5, units = "in")

ggsave("deaths.png", plot = pdeaths, path = path_to_post,
       width = 7, height = 6, units = "in")

```

Next let's try to plot the regression line through Fairfield and other counties.

```{r}
ct2 <- ct %>% mutate(county = fct_collapse(county, Fairfield = "Fairfield", group_other = TRUE)) %>% 
  group_by(county, date) %>% 
  summarise(cases = sum(cases), deaths = sum(deaths))

library(broom)
slopes <- ct2 %>%
  mutate( d = as.numeric(date - min(ct$date))) %>% 
  nest(-county) %>% 
  mutate(
    fit = map(data, ~ lm(log(cases) ~ d , data = .x)),
    tidied = map(fit, tidy)
  ) %>% 
  unnest(tidied)
slopes %>% 
  filter(term == "date") %>% 
  mutate(doubling = exp(log(2) / log(estimate))) %>% 
  select(county, doubling)

slopes %>% 
  filter(term == "d") %>% 
  mutate(doubling = log(2) /estimate) %>% 
  select(county, doubling)

```

```{r}
xx <- ct %>% filter(county = "Fairfield")
```

